import "./globals.css";
import Nav from "./components/Nav";
import TransitionProvider from "./providers/TransitionProviders";

export const metadata = {
  title: "Gallery Block Reveal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TransitionProvider>
          <Nav />
          {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
